
        <?php 
            //fake 404 error generated by cronjob
            http_response_code(404); 
        ?>
        <!DOCTYPE html PUBLIC "-//IETF//DTD HTML 2.0//EN">

<html><head><meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.2.15 (Win64) OpenSSL/3.1.2 PHP/7.2.12 Server at 216.11.12.15 Port 80</address>

</body></html>